### ISSUE TITLE
Get the CI to run the tests

### ISSUE THREAD

**Issue by mariusc** [nodes-ios/serializable-performance-comparison#6]
This is up for discussion, but I think it would be nice if we could get a CI setup to run the performance tests. I'm thinking we can have a folder with JSON files that need to be serialized and deserialized and the CI runs the tests and ideally also outputs the results in a nice way.

**Comment by nickskull** [comment]
This can be done and it would be a nice enhancement and also a starter task for someone to experiment with setting up CI, hooks and outputting data.
